# 构建阶段（编译，这里需要pnpm）
FROM node:18 as build-stage
LABEL maintainer=brian@toimc.com
WORKDIR /app

# 编译阶段需要pnpm
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --registry=https://registry.npmmirror.com

COPY . ./
RUN pnpm run build

# 生产运行阶段（运行业务，不再需要pnpm）
FROM node:18-alpine as production-stage
WORKDIR /app

# 复制编译产物
COPY --from=build-stage /app/dist ./dist
COPY --from=build-stage /app/package.json ./
COPY --from=build-stage /app/pnpm-lock.yaml ./

# 仅安装生产依赖
RUN pnpm install --frozen-lockfile --prod --registry=https://registry.npmmirror.com

EXPOSE 13000



# 运行程序的脚本或者命令
# CMD ["npm", "run", "start:prod"]
CMD ["node","dist/main.js"]
