# 构建阶段（编译，这里需要pnpm）
FROM node:22 as build-stage
LABEL maintainer=brian@toimc.com
WORKDIR /app

# 编译阶段需要pnpm
RUN npm install -g pnpm@11.5.2

COPY package.json pnpm-lock.yaml ./
# ✅增加 --dangerously-allow-all-builds 放行argon2、@nestjs/core的postinstall构建脚本
RUN pnpm install --frozen-lockfile \
  --dangerously-allow-all-builds \
  --registry=https://registry.npmmirror.com


COPY . ./
RUN pnpm run build
# ✅编译完成！再执行一次prod安装，在build‑stage内部产出纯净仅生产依赖的node_modules
RUN pnpm install --frozen-lockfile --prod \
  --dangerously-allow-all-builds \
  --registry=https://registry.npmmirror.com

# ===================== 生产运行阶段 production-stage =====================

# 生产运行阶段（运行业务，不再需要pnpm）
FROM node:22-slim  as production-stage
WORKDIR /app

# 复制编译产物
COPY --from=build-stage /app/dist ./dist
# ✅直接复制已经装好的生产依赖node_modules，运行阶段不用pnpm install
COPY --from=build-stage /app/node_modules ./node_modules
COPY --from=build-stage /app/package.json ./
COPY --from=build-stage /app/pnpm-lock.yaml ./



EXPOSE 13000



# 运行程序的脚本或者命令
# CMD ["npm", "run", "start:prod"]
CMD ["node", "dist/src/main.js"]
